config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root 'items#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get ':controller(/:action(/:id))(.:format)'
  resources :items do
  	get :upvote, 	on: :member
  	get :expensive, on: :collection
  end

  get "admin/users_count" => "admin#users_count"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord

  has_many :comments, as: :commentable

end

app/models/cart.rb
class Cart < ApplicationRecord

	belongs_to :user
	has_many   :positions
	has_many   :items, through: :positions

end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :commentable, polymorphic: true
end

app/models/image.rb
class Image < ApplicationRecord
	mount_uploader :image, ImageUpLoader
	belongs_to :imageable, polymorhic: true
end

app/models/item.rb
class Item < ApplicationRecord

  validates :price, numericality: { greater_than: 0, allow_nil: true }
  # validates :name, :description, presence: true

  validates :name, :price ,presence: true

  has_many :positions
  has_many :carts, through: :positions

  has_many :comments, as: :commentable
  has_many :images,   as: :imageable
  accepts_nested_attributes_for :images

  has_and_belongs_to_many :orders

  # belongs_to :category

  # after_initialize { } #Item.new; Item.first
  # after_save       { } #Item.save; Item.create; Item.update_attributes()
  # after_create     { category.inc(:items_count, 1) }
  # after_update     { }
  # after_destroy	   { category.inc(:items_count, -1) } #Item.destroy

end

app/models/order.rb
class Order < ApplicationRecord

	# attr_accessor :user, :user_id

	belongs_to              :user
	has_and_belongs_to_many :items

	# before_save do
	#   raise "no items in order!" if items.empty?
	# end

    def calculate_total
    	write_attribute :total, items.map(&:price).inject(:+)
    end

end

app/models/position.rb
class Position < ApplicationRecord

	belongs_to :item
	belongs_to :cart

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  validates :login, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one  :cart
  has_many :orders
  has_many :comments

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

	before_filter :check_if_admin
	layout "admin"

	def users_count
		@users_count = User.count
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery with: :exception

  private
    def render_403
    	render file: "public/403.html", status: 403
    end  

    def render_404
    	render file: "public/404.html", status: 404
    end

    def check_if_admin
			render_403 unless params[:admin]
		end

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:login])
    devise_parameter_sanitizer.permit(:account_update, keys: [:login])
  end
		
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	before_action :find_item, only:      [:show, :edit, :update, :destroy, :upvote]
	before_action :check_if_admin, only: [:edit, :update, :new, :create, :destroy]

  def index
    @items = Item
  	@items = @item.where("price >= ?", params[:price_from]) if params[:price_from]
    @items = @items.where("created_at >= ?", 1.day.ago)     if params[:today]
    @items = @items.where("votes_count >= ?", params[:votes_from])     if params[:votes_from]
    @items = @items.order("votes_count DESC", "price")
    # @items = @items.includes(:images)
    # @item.image = params[:file]
  end

  def expensive
  	@items = Item.where("price > 1000")
  	render "index"
  end

  # /items/1 GET
  def show
    # raise "exception test"
  	unless @item 
  		# = Item.where(id: params[:id]).first
  		render text: "Page not found", status: 404
  	end
  end

  # /items/new GET
  def new
  	@item = Item.new
  end

  # /items/1/edit GET
  def edit
  end

  # /items POST
  def create
  	@item = Item.create(item_params)
  	if @item.errors.empty?
  		redirect_to item_path(@item)
  	else
  		render "new"
  	end
  end

  # /items/1 PUT
  def update
  	@item.update_attributes(item_params)
  	if @item.errors.empty?
      flash[:success] = "Item successfully updated!"
  		redirect_to item_path(@item)
  		# redirect_to crop_image_item_path(@item)
  	else
      flash.now[:error] = "You made mistakes in your form"
  		render "edit"
  	end
  end

  # /items/1 DELETE
  def destroy
  	@item.destroy
    render json: { success: true }
    ItemsMailer.item_destroyed(@item).deliver
  	# redirect_to action: "index"
  end

  def upvote
  	@item.increment!(:votes_count)
  	redirect_to action: "index"
  end

	private

		def find_item
			@item = Item.where(id: params[:id]).first
			render_404 unless @item
		end
	
	  def item_params
	   params.require(:item).permit(:name, :description, :price, :real, :weight, :image)		
	  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def urls_to_images(s)
		s.gsub! /\s(http:\/\/.*?(\.(png|jpg)))\s/, '<p><img src="\1"/></p>'
		s.html_safe
	end

	def urls_to_links(s)
		s.gsub! /\s(http:\/\/.*?)\s/, '<a href="\1">\1</a>'
		s.html_safe
	end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admin/users_count.html.erb
There are <%= @users_count %> on the site.

app/views/items/_form.html.erb
<p>Цена: </br><%= f.text_field :price %></p>
<p>Название: </br><%= f.text_field :name %></p>
<p><%= f.file_field :image %></p>
<p>Описание: </br><%= f.text_field :description %></p>
<p>Вес: </br><%= f.text_field :weight %></p>

app/views/items/_form.html.haml
= f.input :price
= f.input :name
= f.input :description
= f.input :weight
= f.input :image

app/views/items/edit.html.erb
<h1>Edit new item</h1>

 <%= form_for @item, html: { multipart: true } do |f| %>

    <%= render partial: "form", locals: { f: f }%>

	<p><%= f.submit "Сохранить товар" %></p>


 <% end %>

app/views/items/edit.html.haml
%h1 Edit new item

=simple_form_for @item, html: { multipart: true } do |f|
  
  = render partial: "form", locals: { f: f }
  %p= f.submit "Сохранить товар"

app/views/items/index.html.erb
<h1>Items</h1>

<% if @items.empty? %>
	<b>No items in store</b>
<% else %>
	<table class="items">
		<tr>
			<th>item id</th>
			<th>Name</th>
			<th>Image</th>
			<th>Price</th>
			<th></th>
			<th></th>
		</tr>

		<% @items.each do |i| %>
		
			<tr data-item_id="<%= i.id %>">
				<td><%= i.id %></td>
				<td><%= link_to i.name, item_path(i) %></td>
				<td><%= image_tag i.image.pathmap("/uploads/images/#{i.image}"), width: '150px', height: '100px' if i.image %></td>
				<td><%= i.price %> руб.</td>
				<td><span class="deleteAction">Удалить</span></td>
				<td>Рейтинг: <%= i.votes_count %>, <%= link_to "+", upvote_item_path(i) %></td>
			</tr>

		<% end %>
	</table>
<% end %>

app/views/items/new.html.erb
<h1>Create new item</h1>
 <%= form_for @item do |f| %>

	<%= render partial: "form", locals: { f: f }%>

	<p><%= f.submit "Создать товар" %></p>


 <% end %>

app/views/items/new.html.haml
%h1 Create new item

= simple_form_for @item do |f| 
  
  = render partial: "form", locals: { f: f }
  %p= f.submit "Создать товар"

app/views/items/show.html.erb
<h2><%= @item.name %></h2>

<ul>
	<li><%= @item.price %>руб.</li>
	<li><%= urls_to_links(urls_to_images(@item.description)) %></li>
	<li><%= t("item.weight") %> <%= @item.weight %>кг.</li>

</ul>
<!-- %h2= @item.name

 %ul
 	%li= "#{@item.price} руб."
	%li= urls_to_links(urls_to_images(@item.description))
	%li
	  = t("item.weight") 
	  = "#{@item.weight} кг." -->

app/views/items/show.html.haml
%h2= @item.name

%ul
	%li= "#{@item.price} руб."
	%li= urls_to_links(urls_to_images(@item.description))
	%li Вес: #{@item.weight} кг.

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyStore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

   <div class="adminPanel">
     Useful links here...
   </div>

   
   <div class="sessionInfo">   

       <% if current_user %>   

           <%= current_user.login %> | <%= link_to 'Sign out', destroy_user_session_path, :method => :delete  %>   

       <% else%>   

           <%= link_to 'Sign in', new_user_session_path %> | <%= link_to 'Registration', new_user_registration_path %>   

       <% end %>   

   </div>
  <p class="notice"><%= notice %></p> 
  <p class="alert"><%= alert %></p> 
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyStore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <div class="sessionInfo">   

       <% if current_user %>   

           <%= current_user.login %> | <%= link_to 'Sign out', destroy_user_session_path, :method => :delete  %>   

       <% else%>   

           <%= link_to 'Sign in', new_user_session_path %> | <%= link_to 'Registration', new_user_registration_path %>   

       <% end %>   

   </div>
  <p style="color: red;"><%= flash[:error] %></p>
  <p style="color: green;"><%= flash[:success] %></p>
  <p class="notice"><%= notice %></p> 
  <p class="alert"><%= alert %></p> 
    <%= yield %>
  </body>
</html>